name: CI/CD Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare remote directory
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 2222
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /home/dev/traefik

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 2222
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: docker-compose.yml
          target: /home/dev/traefik

      - name: Deploy via Docker Compose
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          port: 2222
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/dev/traefik             
            docker-compose up -d --remove-orphans
            docker system prune -f
